design doc
sjsiri/FitNSS pull request #1
Opened 2023-01-17 16:06 UTC by sjsiri

2023-01-17 23:27 UTC, cpenner461 requested changes

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +_List the most important questions you have about your design, or things that you are still debating internally that you might like help working through._
You should remove all of the instructional statements from the doc (unless you still want them for a reminder of what each section is - in that case don't forget to remove them before prospective employers start looking at this).

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +1. FitNSS contains list of exercises pulled form database.
I'm not sure what the actual _questions_ are in questions 1-3. 🤔

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +## 3. Use Cases
A few notes on these.

- Let's think of a few more, we're targeting at least 9 use cases for this.
- U2 and U4 are a little confusing to me - I think it's the use of "Day" that's throwing me off. Maybe a story that explains what the "Day" is within this context.
- U6: I'd clarify what "my experience" means; Is there information that's collected about me when I sign up or is this based on my current activity log?

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +* Keeping logs of more than a week of workouts.
What do you mean by this? (Dynamo will happily let you keep adding data for however many weeks you want)

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +* Interactive UI.
Can you spell out more information about what you mean by this? Reading the "In Scope" items it sounds like there'll be a UI that users can interact with...

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +This initial iteration will provide the minimum viable product (MVP) including adding, retrieving, and updating an employee contact information for the admin role.
"employee contact" ?

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +# 7. Tables
Where will you have a GSI?

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +## 6.2. _GetEmployee Endpoint_
Employee?

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +* Accepts data to update a workout plan including an updated
For this and the other endpoints that accept data (e.g. other PUT/POST) can you describe what the data will need to look like? (e.g. `{"workoutDayName": "Mon", "numberOfSets": 3, ...}`

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +# 6. API
Need to make sure we've got the `DELETE` method being used somewhere.

2023-01-17 23:27 UTC, cpenner461 commented on design-document.md
> +* Accepts `GET` requests to `/exercise`
You show several endpoints that all use the `/exercise` URL with different parameter names. You might want to consider adding an "ExerciseType" parameter to this and using that to figure out whether to return a particular muscle group or movement etc.

2023-01-18 15:59 UTC, sjsiri commented on design-document.md
> +* Accepts `GET` requests to `/exercise`
should it be something like
 /exercise/ExerciseType/:exerciseMovementGroup   
 or     
 /ExerciseType/:exerciseMovementGroup

2023-01-23 15:55 UTC, cpenner461 requested changes

2023-01-23 15:55 UTC, cpenner461 commented on design-document.md
> +U2. As a user, I want to be able to add multiple empty HashMap/Sets/List (Not sure which one to use) that we can add the exercises into.
Let's phrase this in user-facing language instead of the Java types. If you want to keep a reminder that there's a technical decision to make you can add that up under the "questions to resolve" section above.

2023-01-23 15:58 UTC, cpenner461 approved these changes

2023-01-23 16:01 UTC, merged